[build-system]
requires = ["setuptools>=61"]
build-backend = "setuptools.build_meta"

[project]
name = "holoswarm_client"
version = "0.1.0"
requires-python = ">=3.11"
dependencies = [
  "PyYAML",
  "dearpygui",
  "screeninfo",
  "httpx",
  "websockets",
  "Pillow",
  "numpy",
  "matplotlib",
  "rasterio"
]

[project.scripts]
holoswarm-client = "holoswarm_client.app:main"

[tool.setuptools.packages.find]
where = ["src"]
